/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./newTank.glb')
  return (
    <group dispose={null} userData={{ id: props.tankid }}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[0.257, 1.994, -0.591]}
        scale={[1.682, 0.629, 2.559]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.001']}
        position={[0.257, 1.994, -0.591]}
        scale={[1.887, 0.705, 2.871]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials['Material.001']}
        position={[0.268, 5.058, -1.37]}
        scale={[1.582, 0.621, 2.559]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.001']}
          position={[0.002, -1.625, 1.077]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.169, 0.104, 0.429]}
        />
      </mesh>
      <lineSegments
        geometry={nodes.BezierCircle.geometry}
        material={nodes.BezierCircle.material}
        position={[-2.476, 0.943, -0.347]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.218, 2.107, 1.255]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials['Material.001']}
        position={[-2.476, 1.585, 2.908]}
        scale={[1.607, 0.153, 0.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        position={[-1.237, 0.974, 2.619]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.001']}
        position={[-1.862, 1.343, 3.542]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.579}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.001']}
        position={[-1.237, 0.92, 1.223]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['Material.001']}
        position={[-1.237, 0.912, -0.049]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.001']}
        position={[-1.237, 0.897, -1.336]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.001']}
        position={[-1.237, 1.051, -2.855]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials['Material.001']}
        position={[-2.028, 2.191, 1.884]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials['Material.001']}
        position={[-2.028, 2.191, -0.29]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials['Material.001']}
        position={[-2.028, 2.191, -2.342]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials['Material.001']}
        position={[-1.961, 1.284, -3.776]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.479}
      />
      <lineSegments
        geometry={nodes.BezierCircle001.geometry}
        material={nodes.BezierCircle001.material}
        position={[2.907, 0.943, -0.347]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.218, 2.107, 1.255]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.001']}
        position={[2.907, 1.585, 2.908]}
        scale={[1.607, 0.153, 0.158]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.001']}
        position={[4.146, 0.974, 2.619]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials['Material.001']}
        position={[3.521, 1.343, 3.542]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.579}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials['Material.001']}
        position={[4.146, 0.92, 1.223]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials['Material.001']}
        position={[4.146, 0.912, -0.049]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials['Material.001']}
        position={[4.146, 0.897, -1.336]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials['Material.001']}
        position={[4.146, 1.051, -2.855]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.129}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials['Material.001']}
        position={[3.355, 2.191, 1.884]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials['Material.001']}
        position={[3.355, 2.191, -0.29]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials['Material.001']}
        position={[3.355, 2.191, -2.342]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.392}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials['Material.001']}
        position={[3.422, 1.284, -3.776]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.479}
      />
    </group>
  )
}

useGLTF.preload('./newTank.glb')
